<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product_Attribute extends \Product_Attribute implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'attribute_id' => [parent::class, 'attribute_id', null],
        "\0".parent::class."\0".'attribute_item_id' => [parent::class, 'attribute_item_id', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'product_id' => [parent::class, 'product_id', null],
        'attribute_id' => [parent::class, 'attribute_id', null],
        'attribute_item_id' => [parent::class, 'attribute_item_id', null],
        'id' => [parent::class, 'id', null],
        'product_id' => [parent::class, 'product_id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
