<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OrderDetailEntity extends \OrderDetailEntity implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'count' => [parent::class, 'count', null],
        "\0".'*'."\0".'id' => [parent::class, 'id', null],
        "\0".'*'."\0".'order' => [parent::class, 'order', null],
        "\0".'*'."\0".'product' => [parent::class, 'product', null],
        "\0".'*'."\0".'selectedAttributeItem_id' => [parent::class, 'selectedAttributeItem_id', null],
        'count' => [parent::class, 'count', null],
        'id' => [parent::class, 'id', null],
        'order' => [parent::class, 'order', null],
        'product' => [parent::class, 'product', null],
        'selectedAttributeItem_id' => [parent::class, 'selectedAttributeItem_id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
